spring.application.name=dcim

server.port=8081

# Configuración de Base de Datos MySQL local
spring.datasource.url=jdbc:mysql://localhost:3307/dcimdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=

# Configuración JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Ejecutar script de inicialización
spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=false
