apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: clases-app-ingress
  namespace: default
  labels:
    app: clases-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - clases-app.example.com
    secretName: clases-app-tls
  rules:
  - host: clases-app.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: clases-app-service
            port:
              number: 80
