package com.example.dcim.tools;

import java.io.BufferedWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Timestamp;
import java.sql.Types;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.Objects;
import java.util.Properties;

/**
 * Exporta la base MySQL configurada en application.properties a un archivo SQL
 * UTF-8 usando JDBC. Incluye CREATE TABLE y datos INSERT por tabla.
 */
public final class DatabaseExportTool {

    private static final Path APP_PROPERTIES = Paths.get("src", "main", "resources", "application.properties");
    private static final Path DEFAULT_OUTPUT = Paths.get("dcimdb_export.sql");

    private DatabaseExportTool() {
    }

    public static void main(String[] args) throws Exception {
        Path outputPath = args.length > 0 ? Paths.get(args[0]) : DEFAULT_OUTPUT;
        Properties properties = loadDatasourceProperties();

        try (Connection connection = DriverManager.getConnection(
                properties.getProperty("spring.datasource.url"),
                properties.getProperty("spring.datasource.username"),
                properties.getProperty("spring.datasource.password", ""))) {
            exportDatabase(connection, outputPath);
        }

        System.out.println("Export generado en: " + outputPath.toAbsolutePath());
    }

    private static Properties loadDatasourceProperties() throws IOException {
        Properties properties = new Properties();
        try (var reader = Files.newBufferedReader(APP_PROPERTIES, StandardCharsets.UTF_8)) {
            properties.load(reader);
        }
        return properties;
    }

    private static void exportDatabase(Connection connection, Path outputPath) throws SQLException, IOException {
        String catalog = connection.getCatalog();
        List<String> tables = getTables(connection, catalog);

        try (BufferedWriter writer = Files.newBufferedWriter(outputPath, StandardCharsets.UTF_8)) {
            writer.write("-- SQL export generated by DatabaseExportTool\n");
            writer.write("-- Host: localhost    Database: " + catalog + "\n");
            writer.write("-- Generated at: " + LocalDateTime.now() + "\n\n");
            writer.write("SET NAMES utf8mb4;\n");
            writer.write("SET FOREIGN_KEY_CHECKS=0;\n\n");

            for (String table : tables) {
                writeCreateTable(connection, writer, table);
                writeTableData(connection, writer, table);
            }

            writer.write("SET FOREIGN_KEY_CHECKS=1;\n");
        }
    }

    private static List<String> getTables(Connection connection, String catalog) throws SQLException {
        List<String> tables = new ArrayList<>();
        DatabaseMetaData metaData = connection.getMetaData();
        try (ResultSet resultSet = metaData.getTables(catalog, null, "%", new String[]{"TABLE"})) {
            while (resultSet.next()) {
                String table = resultSet.getString("TABLE_NAME");
                if (table != null) {
                    tables.add(table);
                }
            }
        }
        tables.sort(Comparator.naturalOrder());
        return tables;
    }

    private static void writeCreateTable(Connection connection, BufferedWriter writer, String table) throws SQLException, IOException {
        writer.write("--\n");
        writer.write("-- Table structure for table `" + table + "`\n");
        writer.write("--\n\n");
        writer.write("DROP TABLE IF EXISTS `" + table + "`;\n");

        try (Statement statement = connection.createStatement();
             ResultSet resultSet = statement.executeQuery("SHOW CREATE TABLE `" + table + "`")) {
            if (resultSet.next()) {
                writer.write(resultSet.getString(2));
                writer.write(";\n\n");
            }
        }
    }

    private static void writeTableData(Connection connection, BufferedWriter writer, String table) throws SQLException, IOException {
        writer.write("--\n");
        writer.write("-- Dumping data for table `" + table + "`\n");
        writer.write("--\n\n");

        try (Statement statement = connection.createStatement();
             ResultSet resultSet = statement.executeQuery("SELECT * FROM `" + table + "`")) {
            ResultSetMetaData metaData = resultSet.getMetaData();
            int columnCount = metaData.getColumnCount();
            boolean hasRows = false;

            while (resultSet.next()) {
                hasRows = true;
                writer.write("INSERT INTO `" + table + "` (");
                for (int index = 1; index <= columnCount; index++) {
                    if (index > 1) {
                        writer.write(", ");
                    }
                    writer.write("`" + metaData.getColumnName(index) + "`");
                }
                writer.write(") VALUES (");

                for (int index = 1; index <= columnCount; index++) {
                    if (index > 1) {
                        writer.write(", ");
                    }
                    writer.write(toSqlLiteral(resultSet.getObject(index), metaData.getColumnType(index)));
                }

                writer.write(");\n");
            }

            if (!hasRows) {
                writer.write("-- No rows\n");
            }

            writer.write("\n");
        }
    }

    private static String toSqlLiteral(Object value, int sqlType) {
        if (value == null) {
            return "NULL";
        }

        if (value instanceof Boolean booleanValue) {
            return booleanValue ? "1" : "0";
        }

        if (value instanceof Number number && !(value instanceof BigDecimal)) {
            return number.toString();
        }

        if (value instanceof BigDecimal decimal) {
            return decimal.toPlainString();
        }

        if (value instanceof byte[] bytes) {
            return "X'" + toHex(bytes) + "'";
        }

        if (value instanceof Timestamp timestamp) {
            return quote(timestamp.toString());
        }

        if (value instanceof java.sql.Date date) {
            return quote(date.toString());
        }

        if (value instanceof java.sql.Time time) {
            return quote(time.toString());
        }

        if (value instanceof LocalDate localDate) {
            return quote(localDate.toString());
        }

        if (value instanceof LocalTime localTime) {
            return quote(localTime.toString());
        }

        if (value instanceof LocalDateTime localDateTime) {
            return quote(localDateTime.toString().replace('T', ' '));
        }

        if (Objects.equals(sqlType, Types.BIT) || Objects.equals(sqlType, Types.BOOLEAN)) {
            return "1".equals(String.valueOf(value)) ? "1" : "0";
        }

        return quote(String.valueOf(value));
    }

    private static String quote(String value) {
        String escaped = value
                .replace("\\", "\\\\")
                .replace("'", "\\'")
                .replace("\r", "\\r")
                .replace("\n", "\\n");
        return "'" + escaped + "'";
    }

    private static String toHex(byte[] bytes) {
        StringBuilder builder = new StringBuilder(bytes.length * 2);
        for (byte current : bytes) {
            builder.append(String.format("%02x", current));
        }
        return builder.toString();
    }
}